#ifndef ENUMS_H
#define ENUMS_H

enum TOOL {PENCIL, ERASER, CIRCLE, TRIANGLE, RECTANGLE, POLYGON, SELECTOR};

enum COLOR {RED, ORANGE, YELLOW, GREEN, BLUE, INDIGO, VIOLET};

enum ACTION {NONE, UNDO, CLEAR, INCREASE_SIZE, DECREASE_SIZE, BRING_TO_FRONT, BRING_TO_BACK};

#endif